name: my_expenses
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.15.8

flutter:

  uses-material-design: true

  assets:
    - assets/images/pic3.png
    - assets/images/pic5.png

  fonts:
    - family: Gelasio
      fonts:
        - asset: assets/fonts/Gelasio-Regular.ttf
        - asset: assets/fonts/Gelasio-Bold.ttf




